### ISSUE TITLE
Not able to download the data

### ISSUE THREAD

**Issue by Patrik-Br** [kshitijrajsharma/OSMSG#17]
I am running windows, using the OSMSG script over Anaconda Navigator. I am not able to download the data because it stops the process giving me "TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond".
![image](https://user-images.githubusercontent.com/83399473/223134531-4c5fa273-dcc9-46b8-b140-811045db2d3e.png)
. . . . 

![image](https://user-images.githubusercontent.com/83399473/223134738-cf373e31-ea4f-49d8-8737-52f0177bf68d.png)

It might be my slow internet (my download speed is about 9.5 Mbps) and the source website https://planet.openstreetmap.org says "WARNING Download speeds are currently restricted to 4096 KB/s due to limited available capacity on our Internet connection. [Please use torrents](https://wiki.openstreetmap.org/wiki/Planet.osm#BitTorrent) or [a mirror](https://wiki.openstreetmap.org/wiki/Planet.osm#Planet.osm_mirrors) if possible." 
![image](https://user-images.githubusercontent.com/83399473/223133621-e5bf54f3-e1d1-40df-aed4-b9e4d67337d1.png)

**Comment by kshitijrajsharma** [comment]
Hi @Patrik-Br  , Thanks ! Can you pass command that you are using ? I will love to reproduce the issue

**Comment by Patrik-Br** [comment]
My apologise, I forgot to write it there. 

osmsg --username MyUsername --password MyPaSsWoRd --last_week --changeset --charts --name _TEST --users Patrik_B

Statistics for my account for the last week.

**Comment by kshitijrajsharma** [comment]
On normal usage of OSMSG username and password is not required ,It will only be required if you use Geofabrik ! 
Now coming back to your command , If you are looking to extract your user stats you don't need to include --changeset option either ,  `--changeset` option will give you info about hashtags , editors and countries , Mostly for user stats you may not need them . Totally depends upon your usecase 
You can try visualizing the user stats first 
```
osmsg --last_week --charts --name patrik_stats --users Patrik_B
```
if you are trying to extract for a week : you can use `--url day `  or `--url hour` so that you will be only downloading 7 files for a week using day and respective for hour ! this will avoid downloading huge chunk of minute files 

It takes 9 min in my machine to process a week data !

**Comment by Patrik-Br** [comment]
I just tried the 
`osmsg --last_week --charts --name patrik_stats --users Patrik_B`
command, turned on stopwatches and after about 3 and half minutes it got to 28% and then gave me the Windows error

![image](https://user-images.githubusercontent.com/83399473/223693840-d34d3eb6-45f8-41de-9d5a-7086d8815828.png)
![image](https://user-images.githubusercontent.com/83399473/223693983-e74048e4-60ae-4358-87ea-b493976318be.png)

Then I tried the same command again, it started where it ended, so 28%, it got to 30% in about 30 seconds and then stopped again. So probably if I will keep repeating it it will fully download everything. Hmmm will give it a shot later on, I have to go now

**Comment by Patrik-Br** [comment]
After running the command multiple times I was able to get the results
![image](https://user-images.githubusercontent.com/83399473/223750172-0e01ea9c-d2f5-4a0b-b228-b4848cecf5b7.png)

**Comment by kshitijrajsharma** [comment]
Thanks @Patrik-Br  , Your contribution is highly valued !  You can Install latest version of `osmsg `, it has multiple fixes ! 
I will do something about network issue , may be I can make script wait until connects becomes alive or increase max retries , I am brainstorming !
