### ISSUE TITLE
Add version Control 

### ISSUE THREAD

**Issue by kshitijrajsharma** [kshitijrajsharma/OSMSG#44]
Add version control for releasing versions and add it to Documentation

**Comment by hu-yan2023** [comment]
Hello! Could you tell it in detail? I don't understand what version control for releasing versions mean. Thank you!

**Comment by kshitijrajsharma** [comment]
@hu-yan2023 
Something like this 

https://github.com/hotosm/osm-fieldwork/wiki/Version-Control

We can use python packages to manage versions efficiently ! It would be good to have proper documentation and version control on releasing new version of package
