### ISSUE TITLE
Include aggregated statistics 

### ISSUE THREAD

**Issue by jeafreezy** [kshitijrajsharma/OSMSG#6]
Thank you for this great library! I have an idea -- Is it  possible to create basic statistics from the data e.g bar, pie etc for some key data points.

The daily stats is a long list and it's difficult to read the image shared on Twitter,  having a statistics like : Top country, top contributors, top * etc ,I believe will be useful to the general audience.

Then the CSV will always be available for those that want to do some more analysis.

**Comment by kshitijrajsharma** [comment]
Hi jeafreezy, Always thankful for going through ! Yes ! That's a nice Idea ! I was thinking about having charts for top hashtags, top countries and so on and embed them to tweet itself ! Though for top 3 bot will list out them as text, it's a good idea to have them as chart
